inputs:
  - branch: master
    path: .tekton
    type: git
    service: ${github_tron_tektondefinitions}
  - branch: tkn_v1beta1
    path: git
    type: git
    service: ${github_tektoncatalog}
  - branch: tkn_v1beta1
    path: container-registry
    type: git
    service: ${github_tektoncatalog}
  - branch: tkn_v1beta1
    path: kubernetes-service
    type: git
    service: ${github_tektoncatalog}
  - branch: tkn_v1beta1
    path: slack
    type: git
    service: ${github_tektoncatalog}
  - branch: tkn_v1beta1
    path: devops-insights
    type: git
    service: ${github_tektoncatalog}
private_worker: ${private_worker07}
properties:
  # Properties to build operator and test it
  - name: helm-chart
    type: text
    value: "memcached-operator-chart"
  - name: ansible-roles-path
    type: text
    value: ./roles/Memcached
  - name: molecule-scenario-ci-test
    type: text
    value: "test-local"
  - name: molecule-scenario-cd-test
    type: text
    value: "test-cluster"
  - name: toolchain-apikey
    type: secure
    value: ""
  - name: apikey
    type: secure
    value: ""
  - name: operator-image-url
    type: text
    value: us.icr.io/jauninb-tron/memcached-operator
  - name: artifactory-repository-path
    type: text
    value: tron/jauninb
  - name: helm-repository-username
    type: text
    value: jaunin.b@fr.ibm.com
  - name: artifactory-apikey
    type: secure
    value: ""
  - name: deploy-namespace
    type: text
    value: tron-memcached
  - name: github-ibm-com-id_rsa-base64
    type: secure
    value: ""
  - name: github-ibm-com-id_rsa-pub
    type: secure
    value: ""
  - name: test-cluster-name
    type: text
    value: mycluster
  - name: tron-cd-trigger-webhook
    type: text
    value: ""
  - name: X-tron-ci_cd-token
    type: secure
    value: ""
triggers:
  - type: manual
    name: ci-master-manual
    eventListener: ansible-operator-ci-manual
    properties:
      - name: branch
        type: text
        value: "master"
      - name: repository
        type: text
        value: ${operator_repository_url}
  - type: git
    name: ci-master-commit
    eventListener: ansible-operator-ci-github-commit
    service: ${git_operator}
    branch: master
    events:
      push: true
  - eventListener: ansible-operator-test-manual
    name: test-operator-manual
    properties:
      - name: ansible-operator-configs-branch
        type: text
        value: "master"
      - name: ansible-operator-configs-repository
        type: text
        value: ${operator_configs_repository_url}
      - name: delete-release
        type: text
        value: ""
      - name: helm-chart-version
        type: text
        value: ""
      - name: molecule-tests-branch
        type: text
        value: "master"
      - name: molecule-tests-repository
        type: text
        value: ${operator_repository_url}
    type: manual
  # - eventListener: ansible-operator-test-webhook
  #   name: test-operator-webhook
  #   properties:
  #     - name: ansible-operator-configs-branch
  #       type: text
  #       value: "master"
  #     - name: ansible-operator-configs-repository
  #       type: text
  #       value: "https://github.ibm.com/watson-deploy-configs/demo-operator-configs"
  #     - name: delete-release
  #       type: text
  #       value: ""
  #   type: generic
