inputs:
  - branch: master
    path: .tekton
    type: git
    service: ${github_tron_tektondefinitions}
  - branch: tkn_v1beta1
    path: git
    type: git
    service: ${github_tektoncatalog}
  - branch: tkn_v1beta1
    path: container-registry
    type: git
    service: ${github_tektoncatalog}
  - branch: tkn_v1beta1
    path: kubernetes-service
    type: git
    service: ${github_tektoncatalog}
  - branch: tkn_v1beta1
    path: slack
    type: git
    service: ${github_tektoncatalog}
  - branch: tkn_v1beta1
    path: devops-insights
    type: git
    service: ${github_tektoncatalog}
private_worker: ${private_worker}
properties:
  # Properties to build operator and test it
  - name: toolchain-apikey
    # until https://github.ibm.com/org-ids/roadmap/issues/12765 is not fixed
    # type: secure
    type: SECURE
    value: ${toolchain-api-key}
  #
  - name: env_prop-helm-chart
    type: text
    value: ${helm-chart-name}
  #
  - name: github-ibm-com-id_rsa-base64
    # until https://github.ibm.com/org-ids/roadmap/issues/12765 is not fixed
    # type: secure
    type: SECURE
    value: ""
  - name: github-ibm-com-id_rsa-pub
    # until https://github.ibm.com/org-ids/roadmap/issues/12765 is not fixed
    # type: secure
    type: SECURE
    value: ""
  - name: env_prop-ansible-roles-path
    type: text
    value: ${ansible-roles-path}
  #
  - name: env_prop-molecule-scenario-ci-test
    type: text
    value: ${molecule-scenario-ci-test}
  - name: env_prop-molecule-scenario-cd-test
    type: text
    value: ${molecule-scenario-cd-test}
  #
  - name: env_prop-artifactory-server-url
    type: text
    value: ${artifactory-server-url}
  - name: env_prop-artifactory-repository
    type: text
    value: ${artifactory-repository}
  - name: env_prop-artifactory-repository-path
    type: text
    value: ${artifactory-repository-path}
  - name: env_prop-artifactory-username
    type: text
    value: ${artifactory-username}
  - name: artifactory-apikey
    # until https://github.ibm.com/org-ids/roadmap/issues/12765 is not fixed
    # type: secure
    type: SECURE
    value: ${artifactory-api-key}
  #
  - name: apikey
    # until https://github.ibm.com/org-ids/roadmap/issues/12765 is not fixed
    # type: secure
    type: SECURE
    value: ${api-key}
  - name: env_prop-registry-region
    type: text
    value: ${registry-region}
  - name: env_prop-registry-namespace
    type: text
    value: ${registry-namespace}
  - name: env_prop-operator-name
    type: text
    value: ${operator-name}
  - name: env_prop-deploy-region
    type: text
    value: ${deploy-region}
  - name: env_prop-deploy-resource-group
    type: text
    value: ${deploy-resource-group}
  - name: env_prop-deploy-cluster-name
    type: text
    value: ${deploy-cluster-name}
  - name: env_prop-deploy-namespace
    type: text
    value: ${deploy-namespace}
  #
  - name: env_prop-set-up-script
    type: text
    value: ${set-up-script}
  - name: env_prop-tear-down-script
    type: text
    value: ${tear-down-script}
  #
  - name: env_prop-cd-trigger-webhook
    type: text
    value: ""
  - name: ci-cd-operator-token
    # until https://github.ibm.com/org-ids/roadmap/issues/12765 is not fixed
    # type: secure
    type: SECURE
    value: ""
  #
  - name: env_prop-ansible-operator-configs-repository
    type: text
    value: ${operator_configs_repository_url}
  - name: env_prop-ansible-operator-configs-branch
    type: text
    value: "master"
triggers:
  - type: manual
    name: ci-master-manual
    eventListener: ansible-operator-ci-manual
    properties:
      - name: trigger_prop-branch
        type: text
        value: "master"
      - name: trigger_prop-repository
        type: text
        value: ${operator_repository_url}
  - type: git
    name: ci-master-commit
    eventListener: ansible-operator-ci-github-commit
    service: ${git_operator}
    branch: master
    events: { "push": true }
  - type: manual
    eventListener: ansible-operator-cd-manual
    name: cd-operator-manual
    properties:
      - name: trigger_prop-helm-chart-version
        type: text
        value: ""
      - name: trigger_prop-molecule-tests-branch
        type: text
        value: "master"
      - name: trigger_prop-molecule-tests-repository
        type: text
        value: ${operator_repository_url}
  # No way to create generic webhook from template while
  # https://github.ibm.com/org-ids/roadmap/issues/12696 is not fixed
  # - eventListener: ansible-operator-test-webhook
  #   name: test-operator-webhook
  #   properties:
  #     - name: ansible-operator-configs-branch
  #       type: text
  #       value: "master"
  #     - name: ansible-operator-configs-repository
  #       type: text
  #       value: "https://github.ibm.com/watson-deploy-configs/demo-operator-configs"
  #     - name: delete-release
  #       type: text
  #       value: ""
  #   type: generic
