inputs:
  - branch: tkn_v1beta1
    path: git
    type: git
    service: ${githubconsolidated03}
  - branch: tkn_v1beta1
    path: container-registry
    type: git
    service: ${githubconsolidated03}
  - branch: tkn_v1beta1
    path: kubernetes-service
    type: git
    service: ${githubconsolidated03}
  - branch: tkn_v1beta1
    path: slack
    type: git
    service: ${githubconsolidated03}
  - branch: master
    path: .tekton
    type: git
    service: ${github_integrated08}
  - branch: tkn_v1beta1
    path: devops-insights
    type: git
    service: ${githubconsolidated03}
private_worker: ${private_worker07}
properties:
  - name: X-tron-ci_cd-token
    type: secure
    value: ""
  - name: ansible-roles-path
    type: text
    value: ./roles/Memcached
  - name: apikey
    type: secure
    value: ""
  - name: artifactory-apikey
    type: secure
    value: ""
  - name: artifactory-repository-path
    type: text
    value: tron/jauninb
  - name: deploy-namespace
    type: text
    value: tron-memcached
  - name: github-ibm-com-id_rsa-base64
    type: secure
    value: ""
  - name: github-ibm-com-id_rsa-pub
    type: secure
    value: ""
  - name: helm-chart
    type: text
    value: memcached-operator-chart
  - name: helm-repository-username
    type: text
    value: jaunin.b@fr.ibm.com
  - name: molecule-scenario-ci-test
    type: text
    value: test-local
  - name: operator-image-url
    type: text
    value: us.icr.io/jauninb-tron/memcached-operator
  - name: test-cluster-name
    type: text
    value: mycluster
  - name: toolchain-apikey
    type: secure
    value: ""
  - name: tron-cd-trigger-webhook
    type: text
    value: ""
triggers:
  - eventListener: ansible-operator-ci-manual
    name: ci-master-manual
    properties:
      - name: branch
        type: text
        value: "master"
      - name: repository
        type: text
        value: "https://github.com/jauninb/memcached-operator-sample"
    type: manual
  - eventListener: ansible-operator-test-manual
    name: test-operator-manual
    properties:
      - name: ansible-operator-configs-branch
        type: text
        value: "master"
      - name: ansible-operator-configs-repository
        type: text
        value: "https://github.ibm.com/watson-deploy-configs/demo-operator-configs"
      - name: delete-release
        type: text
        value: ""
      - name: helm-chart-version
        type: text
        value: ""
      - name: molecule-tests-branch
        type: text
        value: "master"
      - name: molecule-tests-repository
        type: text
        value: "https://github.com/jauninb/memcached-operator-sample"
    type: manual
  - eventListener: ansible-operator-test-webhook
    name: test-operator-webhook
    properties:
      - name: ansible-operator-configs-branch
        type: text
        value: "master"
      - name: ansible-operator-configs-repository
        type: text
        value: "https://github.ibm.com/watson-deploy-configs/demo-operator-configs"
      - name: delete-release
        type: text
        value: ""
    type: generic
